backend:
  name: github
  repo: tochukwu62/relationshipwisdom
  branch: main
  auth_endpoint: /api/auth
  auth_scope: repo

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "subtitle", label: "Subtitle", widget: "string", required: false }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }